apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "simple-nginx.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Chart.Name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "simple-nginx.fullname" . }}
data:
  health.conf: |-
    server {
      listen 8081 default_server;
      server_name _;
      location / {
        return 200 "I'm alive!";
      }
    }
  {{- range $key, $value := .Values.configs }}
  {{ $key }}.conf: |-
{{ $value | indent 4 }}
  {{- end }}
